joycehwchan/tabinow

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/policies/application_policy.rb

Add devise pundit

---

.gitignore
Gemfile
Gemfile.lock
app/views/layouts/application.html.erb

Added Cloudinary and Mapbox-related Gem, scripts, and styles.

Added Cloudinary and MapBox

---

config/routes.rb

first test push

---

Gemfile.lock
config/environments/development.rb
config/environments/production.rb
config/storage.yml
db/migrate/20221121061701_create_active_storage_tables.active_storage.rb

Added ActiveStorage, and configured it with Cloudinary

Set up ActiveStorage (and added Cloudinary with it)

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/_sidebar.scss
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb
app/views/shared/_sidebar.html.erb

added sidebar skeleton

---

Gemfile
db/seeds.rb

Added Faker and the first version of the seeds.

Added Faker and added the first version of the seeds

---

Gemfile.lock
app/mailers/client_mailer.rb
app/views/client_mailer/Registration.html.erb
app/views/client_mailer/Registration.text.erb
config/environments/production.rb
test/mailers/client_mailer_test.rb
test/mailers/previews/client_mailer_preview.rb

Added ActionMailer (to send emails to the clients)

Started installing and integrating ActionMailer

---

db/migrate/20221121080144_create_addresses.rb
db/migrate/20221121080233_add_columns_to_users.rb
db/migrate/20221121080505_create_itineraries.rb
db/migrate/20221121080515_create_days.rb
db/migrate/20221121080531_create_contents.rb

Cleaned up the mess I made this afternoon with models and migrations :(

restored-models-and-migrations

---

Gemfile.lock
db/migrate/20221121125559_change_data_type_for_phone.rb
db/schema.rb
db/seeds.rb

- Updated the seeds file.
- Changed the data type for Phone in the user database.

Worked more on the seeds and changed the database

---

db/seeds.rb

Changed the way users are selected when it comes to adding seeds.

Changed the way users are selected when adding seeds.

---

Gemfile.lock
app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_devise.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/_sidebar.scss
app/javascript/controllers/index.js
app/javascript/controllers/sidebar_controller.js
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/unlocks/new.html.erb
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb
app/views/shared/_sidebar.html.erb

1. Wrap forms in cards
2. Collapsible Sidebar

style devise forms and sidebar

---

app/models/address.rb
db/schema.rb

Added validations and asociations on address-model.

validations and asociations on address-model

---

package.json
yarn.lock

- Added Sortable for later usage

Added Stimulus Sortable

---

app/controllers/items_controller.rb
app/policies/item_policy.rb
test/controllers/items_controller_test.rb
test/policies/item_policy_test.rb

Items controller

---

app/controllers/days_controller.rb
app/policies/day_policy.rb
test/controllers/days_controller_test.rb
test/policies/day_policy_test.rb

days controller and policy initial

days controller and policy initial

---

app/models/address.rb
app/models/itinerary.rb
app/models/user.rb

Added associations and validations on model itinerary.

Model itinerary

---

app/models/address.rb
app/models/user.rb

Added associations and validations to model user.

associations and validations on user model

---

app/models/itinerary.rb

Added new association to model itinerary.

added new association in relation to content model

---

app/models/day.rb

Associations and validations on model day.

associations and validations on model day

---

app/models/content.rb
app/models/itinerary.rb

Created associations and validations on model content.

associations and validations on model content

---

app/models/user.rb

Removed unnecessary validations on model user.

removed unnecessary validations on model user

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_item_icon.scss
app/assets/stylesheets/components/_status.scss
app/assets/stylesheets/components/_table.scss
app/assets/stylesheets/config/_colors.scss
app/assets/stylesheets/global/_fonts.scss
app/javascript/controllers/sidebar_controller.js
app/views/itineraries/index.html.erb
app/views/itineraries/show.html.erb
app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb

update UI components + layout

---

app/controllers/days_controller.rb
app/controllers/itineraries_controller.rb

Built create method in days controller.

Days#create

---

app/controllers/itineraries_controller.rb

Added flash and authorization to create method.

Itinerary#create

---

app/controllers/itineraries_controller.rb

Built update method for the itinerary controller.

Itinerary#update

---

app/controllers/days_controller.rb
app/controllers/itineraries_controller.rb

Built create method in days controller and new method in the itinerary controller.

build create method in days controller

---

app/models/day.rb
app/models/itinerary.rb
app/models/user.rb
db/migrate/20221122055336_change_referencesin_itineraries.rb
db/migrate/20221122061428_add_email_and_phone_to_itineraries.rb
db/schema.rb
db/seeds.rb

Validation, seed, and migration/db fix

---

Gemfile
Gemfile.lock
app/models/user.rb
db/seeds.rb

Added API call for Hotel names, fixed the deletion of Users, and some verification-related things.

Seed with (some) API, fixed deletion and (some) verification

---

app/controllers/itineraries_controller.rb
app/policies/itinerary_policy.rb

Fixed the pundit authorization for the show page for itineraries.

Fixed bug with the itinerary show page

---

app/models/itinerary.rb
app/views/shared/_sidebar.html.erb
db/seeds.rb

seed update and days number corrected

sidebar and seed fixed error on the days

---

db/schema.rb
db/seeds.rb

- Only one API call for hotels is done when running the seeds
- The same hotel is set for all the days in the itinerary
- Added comments to the code to clarify what everything does
- Changed so that the day count starts at 1, instead of 0

Fixed the API calls in seeds

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_form.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_home.scss
app/assets/stylesheets/pages/_itineraries_show.scss
app/views/devise/confirmations/new.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/itineraries/_table_row.html.erb
app/views/itineraries/show.html.erb
app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb
app/views/shared/_sidebar.html.erb

homepage skeleton + other css fix

---

app/controllers/itineraries_controller.rb
app/javascript/controllers/day_items_controller.js
app/javascript/controllers/index.js
app/views/itineraries/show.html.erb
app/views/shared/_sidebar.html.erb

Section tab

---

app/assets/stylesheets/pages/_itineraries_show.scss

added min width to content container

---

app/assets/stylesheets/pages/_itineraries_show.scss

set both container width to 50%

set both containers to same width

---

app/controllers/itineraries_controller.rb
app/views/itineraries/show.html.erb

Search based on location will require a CSS change

Search for new items

---

app/assets/stylesheets/pages/_itineraries_show.scss
app/views/itineraries/show.html.erb

style search input

---

app/controllers/itineraries_controller.rb
app/views/itineraries/show.html.erb
app/views/shared/_sidebar.html.erb

Enhance search method

---

app/assets/stylesheets/pages/_home.scss
app/views/itineraries/_itinerary.html.erb
app/views/pages/_external_request.html.erb

Update external request form & homepage form

---

db/seeds.rb

Think I solved the problem with how the categories were created now.

Modified the creation of the categories

---

Gemfile
Gemfile.lock
app/services/activities_api_service.rb
config/environments/development.rb
config/environments/test.rb

Bullet
- Installed
- Configured
- Tested
🍪

Intergraded Bullet

---

app/controllers/itineraries_controller.rb
db/seeds.rb

Copy/paste miss in itineraries#new

Miss in itineraries#new

---

db/seeds.rb

Will fetch activities from API to populate the seeds.

Added API calls for activities in Seeds

---

app/assets/stylesheets/components/_sidebar.scss
app/views/itineraries/_content.html.erb
app/views/itineraries/_edit_modal.html.erb
app/views/itineraries/_restaurant_price.html.erb
app/views/itineraries/_sidebar.html.erb

update content card & sidebar

---

app/controllers/itineraries_controller.rb

- Method for creating a category
- Method for creating an item
- If the item is for accommodation, a call to the Accommodation service API is done.

New Category & Item (with accommodation API call)

---

app/services/accommodation_api_service.rb

Missed removing some code from when the API call was used in the seed

Remove code that was not relevant 

---

app/views/itineraries/_table_row.html.erb

Missed deleting a line in the commit that got merged.

Missed deleting line

---

app/assets/stylesheets/pages/_itineraries_index.scss
app/views/itineraries/_edit_modal.html.erb
app/views/itineraries/_table_row.html.erb
app/views/itineraries/index.html.erb

add special request to dashboard and edit modal

---

app/controllers/itineraries_controller.rb

The first version of the call for Restaurant API

Adding restaurants api call

---

app/services/activity_api_service.rb

Set up the service for calling the activity API.

Setting activity api service

---

app/controllers/itineraries_controller.rb

Added API Service for Activities in itineraries controller

Added API Service for Activities in itineraries controller

---

app/controllers/itineraries_controller.rb
app/services/accommodation_api_service.rb

Added the values from the API, also getting some more detailed data for each property

Added the values from accomodations

---

app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb

Added flex-grow =1 to middle section to make sure footer stays at the bottom of the page

added flex grow to middle section + text in top section

---

app/assets/stylesheets/pages/_home.scss
app/views/pages/_external_request.html.erb

change homepage layout + split start and end dates into two row

---

app/controllers/itineraries_controller.rb
app/services/accommodation_api_service.rb

Fixed the accommodation requests after a lot of work... sorry 😞

Fixed the accommodation requests

---

app/controllers/itineraries_controller.rb
app/services/accommodation_api_service.rb
app/services/accommodation_details_api_service.rb
app/services/restaurant_api_service.rb

Accommodations and Restaurants (lunch and dinner) will now populate every day of the itinerary.
(Still need to fix and set same hotel for every day)

Accommodations & Restaurants from API

---

app/controllers/itineraries_controller.rb

This should fix the Accommodation category icon problem.

Fixed the spelling of 'Accommodation' in the itineraries controller.

---

app/controllers/itineraries_controller.rb
app/services/activity_api_service.rb

The itineraries now get the activities from the API.

Added activities to the itineraries controller

---

app/controllers/itineraries_controller.rb
app/models/itinerary.rb

New validation on itinerary duration, and fixed error on itinerary name

itinerary validation and creation of itinerary name error fixed

---

app/controllers/itineraries_controller.rb
app/services/accommodation_api_service.rb
app/services/accommodation_details_api_service.rb
app/services/activity_api_service.rb
app/services/restaurant_api_service.rb

Added retry with rescue in the situations where the API calls fail.

Add retry to api calls

---

app/assets/stylesheets/components/_sidebar.scss
app/controllers/itineraries_controller.rb
app/views/itineraries/_content.html.erb
app/views/itineraries/index.html.erb
app/views/pages/home.html.erb
app/views/shared/_flashes.html.erb

fix show and index css and view

---

app/controllers/itineraries_controller.rb

Had the wrong variable in the conditioning.

The condition for activity budget was messed up

---

app/controllers/itineraries_controller.rb
app/models/itinerary.rb
app/views/itineraries/_create_modal.html.erb
app/views/itineraries/_edit_modal.html.erb
app/views/itineraries/_sidebar.html.erb
app/views/itineraries/_table_row.html.erb
app/views/pages/_external_request.html.erb
db/migrate/20221125024514_rename_name_to_title_in_itineraries.rb
db/schema.rb

the external form was updated with the name and the itinerary name was changed to a title in DB
New migration is needed

Update itinerary form with requester name

---

app/controllers/itineraries_controller.rb
app/views/itineraries/show.html.erb

after the search will remain on the same page without going back to the index

updated search 

---

app/views/itineraries/_create_modal.html.erb
app/views/pages/_external_request.html.erb

add placeholder in external request form

---

app/javascript/controllers/form_controller.js
app/javascript/controllers/index.js
app/views/pages/_external_request.html.erb

@hafid-Qa  Please check this when you have time, thanks!

set minimum value for end date in request form

---

Gemfile
Gemfile.lock
db/schema.rb

js gem linked to binding_of_caller issue removed

remode js gem conflict with binding_of_caller

---

public/500.html

added 500 page

---

Procfile
config/initializers/redis.rb
db/schema.rb

Adding the configuration for Heroku to run redis

Heroku job fix

---

app/views/itineraries/show.html.erb

set hotel filter to selected

---

app/controllers/itineraries_controller.rb
app/policies/itinerary_policy.rb
app/views/itineraries/_table_row.html.erb
db/seeds.rb

Archive an Itinerary without deleting it,  and the  index page will now  show only unarchived itineraries 
duplicate user error in seed, the line has been commented and the name changed to a title for itinerary.
@joycehwchan  can not figure out how to remove the margin-top for the Archive BTN as it caused by the form

Archive itinerary

---

app/controllers/itineraries_controller.rb
app/models/itinerary.rb

I moved the Itinerary logic creation, to the model instead. I believe we can do the same with the accommodation.

Refactor itineraries controller

---

app/javascript/controllers/index.js
app/javascript/controllers/sortable_controller.js
app/views/itineraries/_day.html.erb
package.json
yarn.lock

sorting  day content, please run the below command 
yarn add sortablejs

Sorting day content

---

app/controllers/pages_controller.rb
app/views/itineraries/_create_modal.html.erb
app/views/pages/home.html.erb

add create form modal on homepage

---

app/jobs/accommodation_api_job.rb
app/jobs/activity_api_job.rb
app/jobs/restaurant_api_job.rb
app/models/itinerary.rb
app/services/accommodation_api_service.rb

- Changed the parameters related to the calls for the APIs.
- Refactored some code.

Changed the functions so they work from the Model

---

app/jobs/accommodation_api_job.rb
app/models/content.rb

Added Image to the accommodation

Added IMG to Accommodation

---

app/assets/stylesheets/components/_filter.scss
app/javascript/controllers/filter_controller.js
app/javascript/controllers/index.js
app/views/itineraries/_result.html.erb
app/views/itineraries/_table_row.html.erb
app/views/itineraries/index.html.erb
app/views/itineraries/show.html.erb

Using JS to toggle class "d-none"(display: none) to hide the results.
(Probably not the best way to do this.)

added filter for search results + change archive btns

---

app/controllers/application_controller.rb
app/controllers/itineraries_controller.rb
app/controllers/users/registrations_controller.rb
app/models/itinerary.rb
app/policies/itinerary_policy.rb
app/views/devise/registrations/new.html.erb
app/views/itineraries/_sidebar.html.erb
config/routes.rb

pundit policy for user access and, assign itinerary  to a new user on sign up

Update access policy

---

app/jobs/accommodation_api_job.rb
app/services/accommodation_details_api_service.rb

- One image gets saved to Cloudinary with one image attached through ActiveStorage.
- Refactored some code
- Added the property id in the "api" column in the database.

Added Images to the Accommodation

---

app/jobs/activity_api_job.rb
app/jobs/restaurant_api_job.rb

- Attached images to the restaurants
- Added a restaurant id from yelp to the "API" column

Adding images to restaurants

---

app/jobs/activity_api_job.rb

- Attached images to the activities
- Added a activities id from yelp to the "API" column

Attaching images to the activities

---

db/seeds.rb

- Updated the API-keys
- Updated the seeded Users

Updated the seeds

---

app/jobs/accommodation_api_job.rb
app/models/itinerary.rb

Fixed so that the same hotel is set on every day when the itinerary gets created.

Same hotel on everyday when generated

---

db/migrate/20221128072103_create_unused_contents.rb

Created DB table for Contents that are not used when generating the itinerary

Create DB table for unused Contents

---

db/migrate/20221128071819_create_unused_categories.rb

Created DB table for Categories that are not used when generating the itinerary

Create DB table for unused Categories

---

app/jobs/accommodation_api_job.rb
app/jobs/activity_api_job.rb
app/jobs/restaurant_api_job.rb
app/models/unused_content.rb
db/schema.rb

Saving Accommodation, Restaurants & Activities that are not used to a separate database table

Saving unused contents (Accommodation, Restaurants & Activities)

---

app/controllers/days_controller.rb
app/policies/day_policy.rb
app/views/itineraries/_results.html.erb
config/routes.rb
db/schema.rb

update the content of a day, backend one line need fixing for fine redirect and saving

Add contents to a day

---

app/controllers/days_controller.rb
app/jobs/accommodation_api_job.rb
app/jobs/afternoon_api_job.rb
app/jobs/morning_api_job.rb
db/migrate/20221129041408_add_itinerary_reference_to_unused_content.rb
db/schema.rb

Adding a reference to the Itinerary inside the UnusedContent. This is making sure that the user only has unused content that is relevant to their Itinerary.

Reference to the itinerary for unused content

---

app/assets/stylesheets/components/_content.scss
app/assets/stylesheets/pages/_itineraries_show.scss
app/views/itineraries/_content.html.erb
app/views/itineraries/_results.html.erb

Images are too big in the previous design.

Change card design

---

app/controllers/days_controller.rb
app/jobs/accommodation_api_job.rb
app/jobs/afternoon_api_job.rb
app/jobs/morning_api_job.rb
app/views/itineraries/_map.html.erb
db/migrate/20221130002218_add_coordinates_to_unused_contents.rb
db/schema.rb

Adding the coordinates to all contents and unused_contents

Add coordinates to unused contents

---

Gemfile.lock
app/controllers/contents_controller.rb
app/controllers/items_controller.rb
app/controllers/itineraries_controller.rb
app/javascript/controllers/sortable_controller.js
app/policies/content_policy.rb
app/policies/itinerary_policy.rb
app/views/itineraries/_content.html.erb
app/views/itineraries/_day.html.erb
app/views/itineraries/show.html.erb
config/routes.rb
db/schema.rb
test/controllers/contents_controller_test.rb
test/policies/content_policy_test.rb

customize itinerary content order

Activity order

---

db/migrate/20221130030245_remove_position_from_categories.rb
db/schema.rb
db/seeds.rb

- Removed the migration that was not working.
- Added Admin: true to test users.
- Limited the max days in seeds to 3 instead of 5

Fixed migration and updated seeds

---

app/assets/stylesheets/components/_content.scss
app/assets/stylesheets/components/_map.scss
app/assets/stylesheets/pages/_itineraries_show.scss
app/controllers/itineraries_controller.rb
app/javascript/controllers/map_controller.js
app/views/itineraries/_map_marker.html.erb
app/views/itineraries/_map_popup.html.erb
app/views/itineraries/_overview_sidebar.html.erb

Done:
- Added and styled map-popups
- Added controllers on map
Todo:
- Display correct content that are in the itinerary
- Style markers

Enhance mapbox

---

app/assets/stylesheets/pages/_itineraries_show.scss
app/controllers/itineraries_controller.rb
app/views/itineraries/_map_popup.html.erb
app/views/itineraries/_overview_sidebar.html.erb

- Map now displays only the contents that are in the itinerary.

display correct content(markers) in map

---

app/assets/stylesheets/components/_map.scss
app/assets/stylesheets/pages/_itineraries_show.scss
app/assets/stylesheets/pages/_start.scss
app/javascript/controllers/map_controller.js

- fixed some broken flex css on containers

minor changes on container flex

---

app/assets/stylesheets/components/_form.scss
app/controllers/itineraries_controller.rb
app/jobs/accommodation_api_job.rb
app/jobs/afternoon_api_job.rb
app/jobs/morning_api_job.rb
app/services/activity_api_service.rb
app/views/itineraries/_create_modal.html.erb
app/views/itineraries/_edit_modal.html.erb
app/views/itineraries/_itinerary.html.erb
app/views/itineraries/_sidebar.html.erb
app/views/itineraries/_table_row.html.erb
app/views/layouts/application.html.erb
app/views/pages/_external_request.html.erb
app/views/pages/start.html.erb
db/migrate/20221130052330_remove_special_request_from_itineraries.rb
db/migrate/20221130052505_add_interests_to_itineraries.rb
db/schema.rb
db/seeds.rb

- Added checkboxes to forms to generate an itinerary
- Changed the API requests to use the input from the checkboxes
- Removed the special request column (and places where it was shown

Adding interests to itineraries (and using them to customize the trip)

---

app/controllers/days_controller.rb
app/controllers/itineraries_controller.rb
app/jobs/accommodation_api_job.rb
app/jobs/afternoon_api_job.rb
app/jobs/morning_api_job.rb
app/models/itinerary.rb
app/services/restaurant_api_service.rb
app/views/pages/start.html.erb
config/sidekiq.yml

Code changes to make the generator finish within 30 sec (when the server times out), and avoid 500 error

Making the generator work on Heroku

---

app/controllers/categories_controller.rb
app/controllers/days_controller.rb
app/policies/category_policy.rb
app/views/itineraries/_content.html.erb
config/routes.rb
test/controllers/categories_controller_test.rb
test/policies/category_policy_test.rb

- created category#destroy to remove association (remove content from day)
- add and remove content works now
- Unused content is not created when removing a content

add and remove content works now

---

app/jobs/accommodation_api_job.rb

Making sue day 1 have a hotel

---

app/controllers/itineraries_controller.rb
app/javascript/controllers/map_controller.js
app/models/content.rb
app/models/itinerary.rb

Filtering markers that are buggy and shows up form other parts of the world

Removing markers that are not relevant

---

app/javascript/controllers/share_controller.js
app/views/itineraries/_overview_sidebar.html.erb
app/views/itineraries/_sidebar.html.erb
config/environments/production.rb

Display day

---

app/controllers/itineraries_controller.rb
app/views/itineraries/_sidebar.html.erb
package.json
yarn.lock

Fixed some bugs with Heroku and stuff...

Heroku bug fixes

---

app/javascript/controllers/share_controller.js

pop up for preview

---

app/views/pages/_section_reviews.html.erb

Added some text to Hafid and Chris reviews.

small mods in reviews so they all have the same card size

---

app/views/itineraries/preview.html.erb
config/meta.yml

Added meta tags to itinerary preview

Meta tags preview

---

app/assets/stylesheets/components/_slider.scss
app/views/pages/start.html.erb

Changed the start value for the sliders and the related css for the process bar

Changed the start value for the sliders
